const musicContainer = document.getElementById('music_container'),
    playBtn = document.getElementById('play'),
    nextBtn = document.getElementById('next'),
    prevBtn = document.getElementById('prev'),
    audio = document.getElementById('audio'),
    progress = document.getElementById('progress'),
    progressContainer = document.getElementById('progress-container'),
    title = document.getElementById('title'),
    cover = document.getElementById('cover');